name: blenderproc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.2.1
  - cytoolz=0.12.0
  - dask-core=2022.2.1
  - fftw=3.3.9
  - freetype=2.12.1
  - fsspec=2023.4.0
  - giflib=5.2.1
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lazy_loader=0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - ncurses=6.4
  - networkx=2.8.4
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.0.9
  - partd=1.2.0
  - pip=23.1.2
  - python=3.8.17
  - pywavelets=1.4.1
  - pyyaml=6.0
  - readline=8.2
  - scikit-image=0.20.0
  - scipy=1.9.1
  - setuptools=67.8.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - fonttools==4.40.0
      - h5py==3.9.0
      - idna==3.4
      - importlib-resources==6.0.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.2
      - numpy==1.24.4
      - opencv-python==4.8.0.74
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - progressbar==2.5
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.31.0
      - seaborn==0.12.2
      - six==1.16.0
      - tqdm==4.65.0
      - trimesh==3.22.3
      - tzdata==2023.3
      - urllib3==2.0.3
      - vtk==9.2.6
      - zipp==3.16.0
